# Generated by Django 4.2 on 2023-05-10 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('animal_type', models.CharField(max_length=255, verbose_name='Тип животного')),
                ('breed', models.CharField(blank=True, max_length=255, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=255, verbose_name='Пол')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('health_status', models.TextField(blank=True, verbose_name='Состояние здоровья')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=255, verbose_name='Дом')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('website_link', models.URLField(blank=True, verbose_name='Сайт')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_link', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
            },
        ),
        migrations.CreateModel(
            name='ShelterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shelter_photos/', verbose_name='Фото')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.shelter', verbose_name='Приют')),
            ],
            options={
                'verbose_name': 'Фотография приюта',
                'verbose_name_plural': 'Фотографии приютов',
            },
        ),
        migrations.CreateModel(
            name='MoneyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потраченная сумма')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='money_reports/', verbose_name='Фото')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_reports', to='core.shelter', verbose_name='Приют')),
            ],
            options={
                'verbose_name': 'Отчет о расходах',
                'verbose_name_plural': 'Отчеты о расходах',
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='animal_photos/', verbose_name='Фото')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фотография животного',
                'verbose_name_plural': 'Фотографии животных',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.shelter', verbose_name='Приют'),
        ),
    ]
