# Generated by Django 4.2 on 2023-05-15 00:53

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_age_alter_animal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст (месяцы)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес (граммы)'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
