# Generated by Django 4.2 on 2023-06-15 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_shelter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Начало пребывания в приюте'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание пребывания в приюте'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('in_shelter', 'В приюте'), ('adopted', 'Приютили'), ('missing', 'Отсутствует')], default='in_shelter', max_length=255, verbose_name='Статус животного'),
        ),
    ]
