# Generated by Django 4.2 on 2023-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_animal_created_at_alter_animal_left_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Начало пребывания в приюте'),
        ),
    ]
